### ISSUE TITLE
Upgrade Dependency Versions

### ISSUE THREAD

**Issue by a5anka** [wso2/wso2-axis2-transports#237]
- [ ] jacoco-maven-plugin from 0.8.0 to 0.8.4 #234
- [ ] aspectjweaver from 1.8.5 to 1.9.4 #233
- [ ] aspectjrt from 1.8.5 to 1.9.4 #232
- [ ] maven-bundle-plugin from 1.4.0 to 4.2.0 #229
- [ ] commons-lang from 2.3 to 2.6 #228
- [ ] org.eclipse.paho.client.mqttv3 from 1.2.0 to 1.2.1 #227
- [ ] axis2.version from 1.6.1-wso2v35 to 1.7.9 #226
- [ ] maven-clean-plugin from 2.2 to 3.1.0 #223
- [ ] commons-io from 2.0 to 2.6 #222

**Comment by anupama-pathirage** [comment]
Closing as this is outdated.
